"""Add booking_id column to booking table

Revision ID: a9c909393674
Revises: 275d4b7493ad
Create Date: 2025-11-12 19:16:43.764514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c909393674'
down_revision: Union[str, Sequence[str], None] = '275d4b7493ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('confirmation_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'confirmation_code')
    # ### end Alembic commands ###
